version: '3.8'
services:
  db:
    build: .
    container_name: docker-mysql-hands-on
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: daisuke0218
      MYSQL_DATABASE: name_database
      MYSQL_USER: daisuke
      MYSQL_PASSWORD: daisuke0218
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
